apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: python38-torch-cpu-pr
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/docker/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
          env:
            - name: IMAGE_NAME
              value: python38-torch-cpu
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - image: gcr.io/kaniko-project/executor:v1.8.0-debug
          name: build-containers
          resources: {}
          script: |
            #!/busybox/sh
            set -e
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            
            /kaniko/executor $KANIKO_FLAGS --cleanup --context=/workspace/source/$IMAGE_NAME --dockerfile="Dockerfile" --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$IMAGE_NAME:$VERSION --no-push --tarPath $IMAGE_NAME.tar
        - image: ghcr.io/jenkins-x/trivydb:latest
          name: copy-vulns-db
          resources: {}
          script: |
            #!/bin/sh
            mkdir -p ~/.cache/trivy/db
            mv /trivydb/* ~/.cache/trivy/db/
        - image: aquasec/trivy:0.36.1
          name: vulnscan
          resources: {}
          script: |
            trivy image --timeout 25m0s --security-checks vuln --input /workspace/source/$IMAGE_NAME.tar | tee /workspace/source/scanresults.txt
        - image: ghcr.io/spring-financial-group/container-tools:latest
          name: analyze
          resources: {}
          script: |
            #!/bin/bash
            export PIPELINE_NAME=$(context.pipeline.name)
            export PIPELINE_RUN_NAMESPACE=$(context.pipelineRun.namespace)
            export TEKTON_URL=https://tekton-dashboard.jx.mqube.build/#/namespaces/$PIPELINE_RUN_NAMESPACE/pipelineruns/$PIPELINE_NAME
            source .jx/variables.sh
            cat /workspace/source/scanresults.txt
            if egrep 'HIGH|CRITICAL' /workspace/source/scanresults.txt | grep -v 'Total' | grep -v 'guests via high...' | grep -v "numpy" | grep -v "linux-libc-dev" | grep -v 'vulnerability leads to critical' | grep -v 'python'
            then
            echo "VULNERABILITIES found!" && curl -s -X POST --data-urlencode "payload={\"channel\": \"#alerts-security\", \"username\": \"secalerts\", \"text\": \"HIGH/CRITICAL VULNERABILITY FOUND in $APP_NAME:$VERSION, BUILD STOPPED AND ACCESSIBLE via $TEKTON_URL\", \"icon_emoji\": \":shield:\"}" https://hooks.slack.com/services/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 > /dev/null
            exit 1
            else
            echo "EVERYTHING IS OK"
            fi
        - image: ghcr.io/spring-financial-group/container-tools:latest
          name: push-containers
          resources: {}
          script: |
            #!/bin/bash
            set -e
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson ~/.docker/config.json
            
            crane push /workspace/source/$IMAGE_NAME.tar $PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$IMAGE_NAME:$VERSION
            cosign sign --key k8s://jx-staging/cosign $PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$IMAGE_NAME:$VERSION
            cosign verify --key k8s://jx-staging/cosign $PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$IMAGE_NAME:$VERSION
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
