ignores:
- id: CVE-2026-103111
  reason: "pcre2 in jx3mqubebuild.azurecr.io/spring-financial-group/dotnet-sdk-10:latest (alpine 3.24.2) - fixed in 10.49-r0"
  expires: 2026-12-31
- id: CVE-2026-93990
  reason: "libexpat in jx3mqubebuild.azurecr.io/spring-financial-group/dotnet-sdk-10:latest (alpine 3.24.2) - fixed in 2.8.5-r0"
  expires: 2026-12-31
