ignores:
- id: CVE-2025-69720
  reason: "libncursesw6, libtinfo6, ncurses-base, ncurses-bin in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-103111
  reason: "libpcre2-8-0 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - fixed in 10.46-1~deb13u3"
  expires: 2026-12-31
- id: CVE-2026-12064
  reason: "curl, libcurl4t64 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-16742
  reason: "libpam-systemd, libsystemd-shared, libsystemd0, libudev1, systemd, systemd-sysv in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-34980
  reason: "libcups2t64 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-36849
  reason: "libtiff6 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-52490
  reason: "libtiff6 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-54369
  reason: "libacl1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-66046
  reason: "libexpat1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-6653
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-74860
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-76642
  reason: "bsdutils, libblkid1, liblastlog2-2, libmount1, libsmartcols1, libuuid1, login, mount, util-linux in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-76956
  reason: "libexpat1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-76957
  reason: "libexpat1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-78408
  reason: "bsdutils, libblkid1, liblastlog2-2, libmount1, libsmartcols1, libuuid1, login, mount, util-linux in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-78409
  reason: "bsdutils, libblkid1, liblastlog2-2, libmount1, libsmartcols1, libuuid1, login, mount, util-linux in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-78410
  reason: "bsdutils, libblkid1, liblastlog2-2, libmount1, libsmartcols1, libuuid1, login, mount, util-linux in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-8286
  reason: "curl, libcurl4t64 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-8458
  reason: "curl, libcurl4t64 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86138
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86139
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86140
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86142
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86143
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-86144
  reason: "libxml2 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-88806
  reason: "libx11-6, libx11-data, libx11-xcb1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-88807
  reason: "libxrender1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-8927
  reason: "curl, libcurl4t64 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-93990
  reason: "libexpat1 in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-9538
  reason: "perl-base in jx3mqubebuild.azurecr.io/spring-financial-group/chrome-for-testing:latest (debian 13.7) - No fix reported"
  expires: 2026-12-31
