FROM node:18.13

RUN npm install -g @angular/cli@17.0.9
RUN npm install -g @angular/compiler-cli@17.0.8
RUN npm install -g @angular/language-service@17.0.8
RUN npm install -g typescript@5.2.2

CMD ["bash"]
