#!/usr/bin/env bash
# Regenerates .lighthouse/jenkins-x/triggers.yaml with a PR and release job for every dockerfiles/<category>/<image>/Dockerfile.
# The image name is the dir basename, so it must be unique across categories.
set -euo pipefail

cd "$(dirname "$0")/.."
out=.lighthouse/jenkins-x/triggers.yaml

dirs=$(find dockerfiles -name Dockerfile -exec dirname {} \; | LC_ALL=C sort)

dups=$(printf '%s\n' "$dirs" | xargs -n1 basename | LC_ALL=C sort | uniq -d)
if [ -n "$dups" ]; then
  echo "Duplicate image names found (image name is the dir basename):" >&2
  echo "$dups" >&2
  exit 1
fi

{
  cat <<'EOF'
# Generated by scripts/generate-triggers.sh - do not edit by hand
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
EOF
  for dir in $dirs; do
    cat <<EOF
  - name: ${dir##*/}-pr
    optional: false
    run_if_changed: (LastAutoCommit|^${dir//\//\\/}\/.*$)
    source: "dockerfile-pr.yaml"
    pipeline_run_params:
    - name: IMAGE_DIR
      value_template: ${dir}
EOF
  done
  cat <<'EOF'
  - name: lint-pipelines
    context: "lint-pipelines"
    run_if_changed: '(\.lighthouse\/jenkins-x\/.*|^scripts\/generate-triggers\.sh$|^dockerfiles\/.*\/Dockerfile$)'
    optional: false
    trigger: (?m)^/test( all| lint-pipelines.*),?(s+|$)
    rerun_command: /test lint-pipelines
    source: "lint-pipelines.yaml"
  postsubmits:
  - name: release
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
EOF
  for dir in $dirs; do
    cat <<EOF
  - name: ${dir##*/}-release
    source: "dockerfile-release.yaml"
    branches:
    - ^main$
    - ^master$
    pipeline_run_params:
    - name: IMAGE_DIR
      value_template: ${dir}
EOF
  done
} > "$out"

echo "Wrote $out"
