apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: echo-stuff
        matrix:
            params:
              - name: DOCKERIMAGE
                value:
                  - dotnet6sdk
                  - java11
        resources: {}
        taskSpec:
          params:
            - name: DOCKERIMAGE
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/docker/pullrequest.yaml@versionStream
            name: ""
            resources:
              # override limits for all containers here
              limits: {}
            workingDir: /workspace/source
            env:
              - name: IMAGE_NAME
                value: dotnet6sdk
          steps:
            - name: echo
              image: alpine
              script: |
                  #!/bin/sh
                  echo "$(params.DOCKERIMAGE)"
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
