apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: container-tools-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/container-tools\/.*$
    source: "/container-tools/pr.yaml"
  - name: openjdk14-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/openjdk14\/.*$
    source: "/openjdk14/pr.yaml"
  - name: openjre11-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/openjre11\/.*$
    source: "/openjre11/pr.yaml"
  - name: python310-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/python310\/.*$
    source: "/python310/pr.yaml"
  - name: python310-torch-cpu-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/python310-torch-cpu\/.*$
    source: "/python310-torch-cpu/pr.yaml"
  - name: python310-torch-cuda-pr
    always_run: true
    optional: false
    run_if_changed: ^.*\/python310-torch-cuda\/.*$
    source: "/python310-torch-cuda/pr.yaml"
  postsubmits:
  - name: release
    source: "release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: container-tools-release
    source: "/container-tools/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: openjdk14-release
    source: "/openjdk14/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: openjre11-release
    source: "/openjre11/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-release
    source: "/python310/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-torch-cpu-release
    source: "/python310-torch-cpu/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-torch-cuda-release
    source: "/python310-torch-cuda/release.yaml"
    branches:
      - ^main$
      - ^master$
