apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: container-tools-pr
    optional: false
    run_if_changed: ^.*container-tools\/.*$
    source: "/container-tools/pr.yaml"
  - name: openjdk14-pr
    optional: false
    run_if_changed: ^.*openjdk14\/.*$
    source: "/openjdk14/pr.yaml"
  - name: openjre11-pr
    optional: false
    run_if_changed: ^.*openjre11\/.*$
    source: "/openjre11/pr.yaml"
  - name: python310-pr
    optional: false
    run_if_changed: ^.*python310\/.*$
    source: "/python310/pr.yaml"
  - name: python310-torch-cpu-pr
    optional: false
    run_if_changed: ^.*python310-torch-cpu\/.*$
    source: "/python310-torch-cpu/pr.yaml"
  - name: python310-torch-cuda-pr
    optional: false
    run_if_changed: ^.*python310-torch-cuda\/.*$
    source: "/python310-torch-cuda/pr.yaml"
  - name: nginx-pr
    optional: false
    run_if_changed: ^.*nginx\/.*$
    source: "/nginx/pr.yaml"
  - name: node-pr
    optional: false
    run_if_changed: ^.*node\/.*$
    source: "/node/pr.yaml"
  - name: terra-test-pr
    optional: false
    run_if_changed: ^.*terra-test\/.*$
    source: "/terra-test/pr.yaml"
  postsubmits:
  - name: release
    source: "release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: container-tools-release
    source: "/container-tools/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: openjdk14-release
    source: "/openjdk14/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: openjre11-release
    source: "/openjre11/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-release
    source: "/python310/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-torch-cpu-release
    source: "/python310-torch-cpu/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: python310-torch-cuda-release
    source: "/python310-torch-cuda/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: nginx-release
    source: "/nginx/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: node-release
    source: "/node/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: android-release
    source: "/android/release.yaml"
    branches:
      - ^main$
      - ^master$
  - name: terra-test-release
    source: "/terra-test/release.yaml"
    branches:
      - ^main$
      - ^master$
