ignores:
- id: CVE-2025-26646
  reason: "Microsoft.Build.Tasks.Core in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/dotnet/sdk/8.0.425/FSharp/fsc.deps.json, usr/share/dotnet/sdk/8.0.425/FSharp/fsi.deps.json, usr/share/dotnet/sdk/8.0.425/MSBuild.deps.json, usr/share/dotnet/sdk/8.0.425/NuGet.CommandLine.XPlat.deps.json, usr/share/dotnet/sdk/8.0.425/dotnet.deps.json - fixed in 15.9.30, 16.11.6, 17.8.29, 17.10.29, 17.12.36, 17.13.26, 17.14.8"
  expires: 2026-12-31
- id: CVE-2025-3887
  reason: "gstreamer1.0-plugins-bad, libgstreamer-plugins-bad1.0-0 in jx3mqubebuild.azurecr.io/spring-financial-group/net8-playwright:latest (ubuntu 24.04) - No fix reported"
  expires: 2026-12-31
- id: CVE-2026-47302
  reason: "System.Security.Cryptography.Xml in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/pwsh.deps.json - fixed in 10.0.10, 9.0.18, 8.0.4"
  expires: 2026-12-31
- id: CVE-2026-47304
  reason: "System.Security.Cryptography.Xml in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/pwsh.deps.json - fixed in 10.0.10, 9.0.18, 8.0.4"
  expires: 2026-12-31
- id: CVE-2026-50525
  reason: "System.Security.Cryptography.Xml in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/pwsh.deps.json - fixed in 10.0.10, 9.0.18, 8.0.4"
  expires: 2026-12-31
- id: CVE-2026-50527
  reason: "System.Security.Cryptography.Xml in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/pwsh.deps.json - fixed in 10.0.10, 9.0.18, 8.0.4"
  expires: 2026-12-31
- id: CVE-2026-50648
  reason: "System.Security.Cryptography.Xml in usr/share/dotnet/sdk/8.0.425/DotnetTools/dotnet-format/dotnet-format.deps.json, usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/pwsh.deps.json - fixed in 10.0.10, 9.0.18, 8.0.4"
  expires: 2026-12-31
- id: CVE-2026-62901
  reason: "Microsoft.NETCore.App.Runtime.linux-x64 in usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.10/Microsoft.NETCore.App.deps.json - fixed in 10.0.11, 9.0.19, 8.0.30"
  expires: 2026-12-31
- id: CVE-2026-84782
  reason: "libssl3t64, openssl in jx3mqubebuild.azurecr.io/spring-financial-group/net8-playwright:latest (ubuntu 24.04) - fixed in 3.0.13-0ubuntu3.16"
  expires: 2026-12-31
