name: Python3.8 Image

on:
  schedule:
    - cron:  '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout v2
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}

    - name: Build the Docker image
      run: |
        docker build dotnet6sdk -t ghcr.io/spring-financial-group/dotnet6sdk:latest
        docker push ghcr.io/spring-financial-group/dotnet6sdk:latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      USER: ${{ secrets.USER }}